#!/bin/bash

cd ~
 
# Install arduino-cli
apt-get install curl -y
curl -L -o arduino-cli.tar.bz2 https://downloads.arduino.cc/arduino-cli/arduino-cli-latest-linux64.tar.bz2
tar xjf arduino-cli.tar.bz2
rm arduino-cli.tar.bz2
mv `ls -1` /usr/bin/arduino-cli

# Install 'native' packages
arduino-cli lib install "Adafruit BME280 Library"
arduino-cli lib install "Adafruit Unified Sensor"
arduino-cli lib install "HCSR04 ultrasonic sensor"
arduino-cli lib install "ArduinoJson"
arduino-cli lib install "MPU9250_asukiaaa"
cd -
 
# Install 'third-party' packages: find proper location and 'git clone'
apt-get install git -y
cd `arduino-cli config dump | grep sketchbook | sed 's/.*\ //'`/libraries
git clone https://github.com/me-no-dev/AsyncTCP.git
git clone https://github.com/me-no-dev/ESPAsyncWebServer.git
git clone https://github.com/ThingPulse/esp8266-oled-ssd1306.git
git clone https://github.com/RoboticsBrno/ESP32-Arduino-Servo-Library.git
